/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2022-05-09 14:17:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.LoanModel;

public final class CustomerLoan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
 	
	LoanModel lnMdl = (LoanModel) session.getAttribute("lnMdl");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("      <p>Status </p>\r\n");
      out.write("      <p>Repayment Status:");
      out.print( lnMdl.status );
      out.write(" </p>\r\n");
      out.write("      <h1>Coin Flipper ");
      out.print(lnMdl.repaymentStatus );
      out.write("</h1>\r\n");
      out.write("      <p>Flipping a coin...</p>\r\n");
      out.write("         <h1>Coin Flipper</h1>\r\n");
      out.write("    \t");
 if(lnMdl.status == 0 ){ 
      out.write("\r\n");
      out.write("      \t\t<p>You have no loans!</p>\r\n");
      out.write("    \t");
 } else{ 
      out.write("\r\n");
      out.write("    \t\t");
 String[][] loanTable = lnMdl.getLoanTable(); 
      out.write("\r\n");
      out.write("    \t\t");
 for( int i = 0; i < loanTable.length; i++){ 
      out.write("\r\n");
      out.write("      \t\t\t\t\t<p>Tails!");
      out.print(loanTable[i][0]);
      out.write("</p>\r\n");
      out.write("      \t\t\t\t\t<p>Tails!");
      out.print(loanTable[i][1] );
      out.write("</p>\r\n");
      out.write("      \t\t\t\t\t<p>Tails!");
      out.print(loanTable[i][2] );
      out.write("</p>\r\n");
      out.write("      \t\t\t\t\t<p>Tails!");
      out.print(loanTable[i][3] );
      out.write("</p>\r\n");
      out.write("      \t\t\t\t\t<p>Tails!");
      out.print(loanTable[i][4] );
      out.write("</p>\r\n");
      out.write("      \t\t\t\t\t<p>Tails!");
      out.print(loanTable[i][5] );
      out.write("</p>\r\n");
      out.write("      \t\t\t\t\t<p>Tails ");
      out.print(i );
      out.write("</p>\r\n");
      out.write("    \t");
 }} 
      out.write("\r\n");
      out.write("    \t<hr>\r\n");
      out.write("\t\t\t<a href=\"./ApplyLoan.jsp\">Apply Loan</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("    <hr>\r\n");
      out.write("   </body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
